encoding: utf-8

# SEO相关信息
title: MESC CLUB
description: Marine Engineering Study Center
keywords: study，academic,tools,experience
footerText: 'Copyright © 2020 MESC'

paginate: 12
paginate_path: "page/:num/"

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://yhyates.github.io'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/products/127971

# 菜单
menu:
  - title: 首页
    url: /
  - title: 分类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 反馈
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: false

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: false

# 百度收录自动推送,不需要请设置为false
extBaidu: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: true



